<a href="https://colab.research.google.com/github/sarahbraia/statistics-with-python/blob/main/4_qui_quadrado_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Qui Quadrado

In [ ]:
# Importação das funções, chi2_contingency porque temos 2 categorias
import numpy as np
from scipy.stats import chi2_contingency

In [ ]:
# Criação da matriz com os dados e execução do teste
# Criando a matriz de contingência (linhas = sexo, colunas = assiste/não assiste)
# Linha 1: Masculino (19 assiste, 6 não assiste)
# Linha 2: Feminino (43 assiste, 32 não assiste)
novela = np.array([[19, 6], [43, 32]])
novela

array([[19,  6],
       [43, 32]])

Teste do Qui-Quadrado de Independência:

Hipótese nula (H₀): Não há associação entre o gênero e o fato de assistir.

Hipótese alternativa (H₁): Existe associação entre o gênero e o fato de assistir.

In [ ]:
# Aplicando o teste do Qui-Quadrado
chi2, p, dof, expected = chi2_contingency(novela)

# Exibindo os resultados
print(f"Estatística Qui-Quadrado: {chi2:.4f}")
print(f"Valor-p: {p:.4f}")
print(f"Graus de liberdade: {dof}")
print("Frequências esperadas:")
print(expected)


Estatística Qui-Quadrado: 2.0374
Valor-p: 0.1535
Graus de liberdade: 1
Frequências esperadas:
[[15.5  9.5]
 [46.5 28.5]]


In [ ]:
# Criação da matriz com os dados e execução do teste
# Criando a matriz de contingência (linhas = sexo, colunas = assiste/não assiste)
# Linha 1: Masculino (22 assiste, 3 não assiste)
# Linha 2: Feminino (43 assiste, 32 não assiste)
novela2 = np.array([[22, 3], [43, 32]])
novela2

array([[22,  3],
       [43, 32]])

In [ ]:
# Aplicando o teste do Qui-Quadrado
chi2, p, dof, expected = chi2_contingency(novela2)

# Exibindo os resultados
print(f"Estatística Qui-Quadrado: {chi2:.4f}")
print(f"Valor-p: {p:.4f}")
print(f"Graus de liberdade: {dof}")
print("Frequências esperadas:")
print(expected)


Estatística Qui-Quadrado: 6.4615
Valor-p: 0.0110
Graus de liberdade: 1
Frequências esperadas:
[[16.25  8.75]
 [48.75 26.25]]


In [ ]:
#agora valor de p menor que 0,05, podemos rejeitar a hipótese nula em favor da hipótese alternativa: há diferença significativa